site_name: Homelab Infra
site_url: https://michaelheaton.github.io/homelab-infra/
repo_url: https://github.com/MichaelHeaton/homelab-infra
repo_name: MichaelHeaton/homelab-infra

theme:
  name: material
  logo: assets/logo.svg
  features:
    - navigation.top
    - content.code.copy
    - toc.integrate
    - navigation.sections
    - navigation.footer
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MichaelHeaton

markdown_extensions:
  - abbr
  - meta
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - toc:
      toc_depth: 2
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - docs

hooks:
  - hooks.py

plugins:
  - search

nav:
  - Home: index.md
  - Hardware: 01-Hardware.md
  - Workstation Setup: 02-Workstation-Setup.md
  - Cloud Accounts & Foundations: 03-Cloud-Accounts-and-Foundations.md
  - Network Setup: 04-Network-Setup.md
  - NAS Setup: 05-NAS-Setup.md
  - Proxmox Cluster Setup: 06-Proxmox-Cluster-Setup.md
  - Reference:
    - AI Context: ai-context.md
    - Glossary: glossary.md
  - Runbooks:
    - Resolve Conflicts: runbooks/resolve_conflicts.md
    - Vault Bootstrap Runbook: runbooks/vault_bootstrap_runbook.md
