site_name: Homelab Infra
site_url: https://michaelheaton.github.io/homelab-infra/
repo_url: https://github.com/MichaelHeaton/homelab-infra
repo_name: MichaelHeaton/homelab-infra

theme:
  name: material
  features:
    - navigation.top
    - content.code.copy
    - toc.integrate
    - navigation.sections
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MichaelHeaton

markdown_extensions:
  - meta
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

nav:
  - Home: index.md
  - Hardware: hardware.md
  - Workstation Setup: workstation-setup.md
  - Cloud Control Plane Setup: cloud-control-plane-setup.md
  - Foundations: phase1-foundations.md
  - Networking & Access: phase2-networking.md
  - Storage & Backups: phase3-storage-backups.md
  - Observability: phase4-observability.md
  - Security: phase5-security.md
  - First Workloads: phase6-first-workloads.md
  - Migration: migration.md
  - Control Plane: control-plane.md
  - Release: release.md
  - Reference:
      - Glossary: glossary.md
      - AI Context: ai-context.md
  - Runbooks:
    - resolve conflicts: runbooks/resolve_conflicts.md
    - vault Uootstrap runUook: runbooks/vault_bootstrap_runbook.md
