site_name: Homelab Infra
site_url: https://michaelheaton.github.io/homelab-infra/
repo_url: https://github.com/MichaelHeaton/homelab-infra
repo_name: MichaelHeaton/homelab-infra

theme:
  name: material
  logo: assets/logo.svg
  features:
    - navigation.top
    - content.code.copy
    - toc.integrate
    - navigation.sections
    - navigation.footer
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MichaelHeaton

markdown_extensions:
  - abbr
  - meta
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - toc:
      toc_depth: 2
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - docs

hooks:
  - hooks.py

plugins:
  - search

nav:
  - Home: index.md
  - Hardware: 01-Hardware.md
  - Workstation Setup: 02-Workstation-Setup.md
  - Cloud Accounts & Foundations: 03-Cloud-Accounts-and-Foundations.md
  - Network Setup & Terraform Imports: 04-Network-Setup.md
  - NAS Setup: 05-NAS-Setup.md
  - Proxmox Cluster Setup: 06-Proxmox-Cluster-Setup.md
  - CI/CD for Terraform: 07-CI-CD-for-Terraform.md
  - Image Factory: 08-Image-Factory.md
  - Core Infra VMs: 09-Core-Infra-VMs.md
  - Docker Swarm Cluster: 10-Docker-Swarm-Cluster.md
  - Traefik + Authentik + Public DNS + VPN: 11-Traefik-Authentik-Public-DNS-VPN.md
  - Integration Pass: 12-Integration-Pass-1.md
  - Migrations & Refactor: 13-Migrations-and-Refactor.md
  - Observability + Alerting: 14-Observability-and-Alerting.md
  - Ops Readiness: 15-Ops-Readiness.md
  - Local DNS: 16-Local-DNS.md
  - DMZ & Routing: 17-DMZ-and-Routing.md
  - Public Status Page + Alerting: 18-Public-Status-Page-and-Alerting.md
  - Workloads: 19-Workloads.md
  - Graduation: 20-Graduation.md
  - Lab & Service Ideas: 21-Lab-and-Service-Ideas.md
  - Reference:
    - AI Context: ai-context.md
    - Glossary: glossary.md
  - Runbooks:
    - Resolve Conflicts: runbooks/resolve_conflicts.md
    - Vault Bootstrap Runbook: runbooks/vault_bootstrap_runbook.md
