site_name: Homelab Infra
site_url: https://michaelheaton.github.io/homelab-infra/
repo_url: https://github.com/MichaelHeaton/homelab-infra
repo_name: MichaelHeaton/homelab-infra

theme:
  name: material
  features:
    - navigation.top
    - content.code.copy
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MichaelHeaton

markdown_extensions:
  - meta
  - admonition
  - toc:
      permalink: true

plugins:
  - search

nav:
  - Home: index.md
  - Hardware: hardware.md
  - Phase 0: phase0.md
  - Phase 1: phase1.md
  - Phase 2: phase2.md
  - Phase 3: phase3.md
  - Phase 4: phase4.md
  - Phase 5: phase5.md
  - Phase 6: phase6.md
  - Migration: migration.md
  - Control Plane: control-plane.md
  - Release: release.md
  - Runbooks:
    - Resolve Conflicts: runbooks/resolve_conflicts.md
    - Vault Bootstrap: runbooks/vault_bootstrap_runbook.md
