---
# Home: https://gethomepage.dev
# Synology NAS: mkdir -p /volume1/docker/appdata/homepage/{config}
# Hard link .env: ln /volume1/docker/appdata/.env /volume1/docker/appdata/homepage/.env
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    logging:
      driver: "json-file"
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 3000:3000
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
